export enum ConfigName {
    "USE_HEADLESS" = "USE_HEADLESS",
    "APP_NAME" = "APP_NAME",
    "HANDLER_TIMEOUT" = "HANDLER_TIMEOUT",
    "HANDLER_ATTEMPT" = "HANDLER_ATTEMPT",
    "PAGE_ATTEMPT" = "PAGE_ATTEMPT",
    "BROWSER_CONNECT" = "BROWSER_CONNECT",
}
