name: Ci Job

on:
  push:
    branches: [ main, master ]
  pull_request_target:

jobs:
  review-and-test:
    name: lint / tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 24 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Bun Install
        run: bun install --frozen-lockfile
      - name: Get Playwright Version
        run: echo "PLAYWRIGHT_VERSION=$(bun pm ls | grep playwright | awk '{print $2}')" >> $GITHUB_ENV
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers (if cache miss)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: bunx playwright install chromium
      - if: ${{ github.event_name == 'pull_request' }}
        name: Review Dog Pull Request
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GH_TOKEN }}
          eslint_flags: .
          fail_on_error: true
      - name: Build Code
        run: bun run build
      - name: Run Tests
        env:
          USE_HEADLESS: "true"
        run: bun run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
      - if: ${{ github.event_name == 'push' && vars.IS_PACKAGE == 'true' }}
        name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bunx semantic-release
